### ISSUE TITLE
Bug: Knife Execution breaks view and UI

### ISSUE THREAD

**Issue by MarshalRed** [DS-13-Dev-Team/DS13-1.0#1867] opened 2021-10-10 20:41 UTC
#### Description of issue:
View breaks if the knife hits a helmet or you get interrupted. UI Gets Squished together. While this is happening you cannot perform another execution.

#### Difference between expected and actual behavior:
Should just reset after failure.

#### Steps to reproduce:
Get interrupted or perform a sacrifice on a helmeted target.

**Comment by Snypehunter007** [comment] 2021-10-10 21:56
Duplicate of #1408.

Closing.

**Closed as completed by Snypehunter007** 2021-10-10 21:56 UTC
Labels: Duplicate
