### ISSUE TITLE
[BUG] Lurker - Retract Shell Zoom

### ISSUE THREAD

**Issue by ArcadeDan** [DS-13-Dev-Team/DS13-1.0#356] opened 2020-05-14 19:34 UTC
Whenever I use the retract shell verb, it'll zoom out so I have a bigger viewing radius. This seems intentional, however, it strectedddddd

![dreamseeker_2020-05-14_14-34-18](https://user-images.githubusercontent.com/21047549/81977699-0cf08380-95f0-11ea-9cf4-cac7bd922e87.png)

**Comment by Snypehunter007** [comment] 2020-05-14 20:58
Sorta a duplicate of #173. Closing.

**Closed as completed by Snypehunter007** 2020-05-14 20:58 UTC
Labels: Duplicate
