### ISSUE TITLE
Suggestion: Nerf hand and feet meta for necros

### ISSUE THREAD

**Issue by saltprjak** [DS-13-Dev-Team/DS13-1.0#1454] opened 2021-05-31 21:50 UTC
#### Suggestion:
Nerf necromorphs targetting exposed hands and feet to bypass armor, by following in Bay12s steps and making attacks to hands and feet transfer to arms and legs respectively.

#### What do you think it'd add:
As it stands, targetting hands and feet for necromorphs often allows them a very unfair and (i presume) frustrating advantage of bypassing any sort of armor. Riot armor and the like leaves hands and feet exposed, while losing one limb completely exposes the other due to gloves and boots being dropped when it comes to RIGs. This trivializes armored opponents and makes necromorph attacks feel way too gamey.
This change will give survivors more of fighting chance based on their gear and reduce death "cheapness".

**Comment by MarshalRed** [comment] 2021-06-11 13:22
Same could be said for spitters/pukers aiming for eyes and groin targeting by most melee necros.

**Comment by NanakoAC** [comment] 2021-06-27 05:27
> 
> 
> Same could be said for spitters/pukers aiming for eyes and groin targeting by most melee necros.

spitters aiming for the eyes is completely intended behaviour
the groin has the same total health as both legs and is not any more efficient

**Comment by NanakoAC** [comment] 2021-06-27 05:49
I have a simple solution for fixing this. A tweak to make hands and feet not severable. 
Damaging them is fairly meaningless if they can't be cut off, the attacker would need to target the arm or leg instead

**Comment by Snypehunter007** [comment] 2021-09-30 19:49
We recently nerfed hand and feet meta. I consider this suggestion, as it currently is, complete.

Closing.

**Closed as completed by Snypehunter007** 2021-09-30 19:49 UTC
Labels: Suggestion: Accepted
