### ISSUE TITLE
[Bug] Turrets don't die.

### ISSUE THREAD

**Issue by TheMaskedMan2** [DS-13-Dev-Team/DS13-1.0#380] opened 2020-05-16 07:41 UTC
![Turret Bug](https://i.gyazo.com/69e1d4b104822d6ad52f4764d2f3b136.png)

Not sure what is up with these things, but I was testing locally how sentries work and such, and basically they never seem to die. I've detonated exploders on it, shot it with spitters, tried slashing it, throwing grenades at it.

The image is of the aftermath of all my attempts to kill this sentry.

**Comment by Snypehunter007** [comment] 2020-06-14 16:10
Sort of a duplicate of #326.

Locking.

**Closed as completed by Snypehunter007** 2020-06-14 16:10 UTC
Labels: Duplicate
