### ISSUE TITLE
Linegun shoots through solids

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#1146] opened 2021-01-10 19:29 UTC
Description of issue: Weapon bug for the Linegun.

Difference between expected and actual behavior: The Linegun should probably shoot in a straight-ish arc forward, and not through solid objects without breaking them. Instead, it can shoot through glass windows perfectly fine in-game. I've seen survivors kill necromorphs that way.

Steps to reproduce: Shoot the Linegun through a window, probably on a tile bordering the window.

**Comment by JakeDaBoss** [comment] 2021-01-10 19:32
Additional report by EugeneShev (Pufferfish Eating A Carrot)

If I recall properly, cutters still pass through transparent objects, but recently I've figured it also ignored machines and whatnot. Not that they're not transparent, I just suspected it would work more like a laser that still hits the machinery. I certainly remember a line gun passing through the fridge, at least.

**Comment by Snypehunter007** [comment] 2021-02-02 19:42
Duplicate of #1026.

Closing.

**Closed as completed by Snypehunter007** 2021-02-02 19:42 UTC
Labels: Duplicate
