### ISSUE TITLE
Suggestion: Rig Move Speed Variation.

### ISSUE THREAD

**Issue by MarshalRed** [DS-13-Dev-Team/DS13-1.0#1489] opened 2021-06-09 15:45 UTC

**Comment by NanakoAC** [comment] 2021-06-11 18:59
We already have this
defines/rig.dm

```
/*
	Defines for rig slowdown values
*/

#define RIG_VERY_LIGHT	0
#define RIG_LIGHT	1.25
#define RIG_FLEXIBLE	1.5
#define RIG_MEDIUM	1.75
#define RIG_HEAVY	2
#define RIG_VERY_HEAVY	2.5
#define RIG_SUPER_HEAVY	3
```

Values vary in seven different categories, they have been tweaked extensively, and revised downwards several times (heaviest rigs used to be 5 slowdown)

The slowdown imparted by a rig is one of the most important factors considered in balancing.
Perhaps the issue is just that its not really made clear to the end user? These speed differences might be hard to percieve unless you're comparing with someone else, but they definitely have an impact on combat

As for moving faster generally, we're getting a sprint system very soon

**Comment by MarshalRed** [comment] 2021-06-11 19:47
I see.

**Comment by Snypehunter007** [comment] 2021-09-14 15:20
Closing, since we already have the system.

**Closed as completed by Snypehunter007** 2021-09-14 15:20 UTC
Labels: Invalid
