### ISSUE TITLE
[Issue] Disposals make people immortal.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#939] opened 2020-10-17 23:39 UTC
#### Description of issue:
Disposal units can't be destroyed, and won't work if power is shut off. Hence people can just sit in a disposal unit, and necros can't  touch them at all.

**Comment by Snypehunter007** [comment] 2020-10-18 18:38
Duplicate of #898.

Closing.

**Closed as completed by Snypehunter007** 2020-10-18 18:38 UTC
Labels: Duplicate
