### ISSUE TITLE
(BUG) Exosuit fabricators don't work

### ISSUE THREAD

**Issue by githubuser4141** [DS-13-Dev-Team/DS13-1.0#870] opened 2020-09-19 23:49 UTC
#### Description of issue:

Exosuit fabricators don't work, building them in RnD is pointless, it can't find the RnD console and has no designs

#### Difference between expected and actual behavior:

Though it'd be neat to make a mech fabricator to make robolimbs and mechs, turns out it couldn't do either

#### Steps to reproduce: 

Start playing, go to RnD (or anywhere, probably) build a exofab machine, try to use it.

**Comment by Snypehunter007** [comment] 2020-09-20 01:24
Not a bug, intentional, since they don't fit the universe's lore.

Closing.

**Closed as completed by Snypehunter007** 2020-09-20 01:24 UTC
Labels: Invalid
