### ISSUE TITLE
BUG: Extended View Range Blackscreen when facing left

### ISSUE THREAD

**Issue by PrimusOmega** [DS-13-Dev-Team/DS13-1.0#774] opened 2020-08-29 22:54 UTC
Description of issue:  Extended view range seems to be causing some pretty strange issues this first round.  When looking specifically west with an extended view range, your screen will go completely black unless you physically orient your sprite in a different direction by blindly clicking or moving your character.  This has been confirmed to be an issue so far with the Plasma Cutter, the Twitcher, and the Leaper with their extended view range by various players.  Likely carries over to other necros and weapons as well that haven't been tested.  I would recommend that you test any necro with a skewed/extended view range and other weapons with a scope in function.  Also seem to be occasionally be having east view skew in the wrong direction, with the view to the right being shorter than the view to the left.  

Difference between expected and actual behavior: Players should not be going blind by using their eyes/weapons in a certain direction.

Steps to reproduce: 
Spawn a Twitcher or Leaper.  Possess the necromorph of choice.  Orient your sprite to the left by either moving left or clicking to the left.  Your screen will promptly go black except for your HUD.  Reportedly also happens when using plasma cutter right click to look further when looking left, but have not tested it yet personally.

Round Info: 
Not sure if this is useful, but including this info just in case.
Client Version: 513
Server Revision: Revision Unknown
Game ID: b8S-djzZ
Current map: USG Ishimura

**Comment by NanakoAC** [comment] 2020-08-30 01:10
Duplicate of #773 
I got there first :P

**Closed as completed by NanakoAC** 2020-08-30 01:10 UTC
Labels: Duplicate
