### ISSUE TITLE
[BUG] Right hand.exe stopped working.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#392] opened 2020-05-23 22:01 UTC
#### Description of issue
When you have a container open, you can't use the right hand.

#### Steps to reproduce 
Open a container, try to use your right hand. You can't.

**Comment by NanakoAC** [comment] 2020-05-24 00:42
Cannot reproduce, need more info. Can you specify an exact kind of container?

**Comment by Ketrai** [comment] 2020-05-24 01:21
This is the info I got, I'll have to ask around. Ask bill canister either way

**Comment by Snypehunter007** [comment] 2020-05-26 22:54
Fixed in #395.

Closing.

**Closed as completed by Snypehunter007** 2020-05-26 22:54 UTC
Labels: Fixed
