### ISSUE TITLE
twitchers can step slice themselves.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#118] opened 2020-03-07 22:33 UTC
#### Description of issue
twitchers can target themselves with abilities, there also doesn't seem to be a hotkey.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Snypehunter007** [comment] 2020-03-08 00:12
Duplicate of #51 

Closing.

**Closed as completed by Snypehunter007** 2020-03-08 00:12 UTC
Labels: Duplicate
