### ISSUE TITLE
[BUG] Tripod issues megaissue.

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#391] opened 2020-05-23 21:50 UTC
#### Description of issue
1. tripod sprite can be seen through walls/other vision obstructing obstacles.
2. tripod probably shouldn't  take full body damage. rather aim for the limbs to kill it.
3. arm swipe disarming/knocking people down is a bit opressive. Tripod can already knock people down with leap, the potential for chain-stunning is too high.
4. it can be put into lockers, and disposaled, and buckled to things. You can esentially buckle it  to a surgery table and amputate it too, which makes little sense. This is an issue for big necromorphs in general.
5. The tongue can be hit and dismembered even when it isn't exposed, making it incredibly hard to use tongue lash or kiss of death, especially as it has low limb hp.
6. It seems in some cases the momentum speed mechanic for the leaper breaks. perhaps after being knocked down, rejuvinated, or otherwise.
7. tripod can jump into walls and other obstructing obstacles, allowing them to phase through them. Great for scares, but not very logical.

**Comment by NanakoAC** [comment] 2020-05-23 23:14
1. not clear what is meant here, need demonstration
2. It takes 0.75* body damage, maybe this is too much
3. Working as intended, oppression is its role. Not that it can't change, but being able to whack people around is an important part of its strategy
4. All bugs, will fix
5. bug
6. Sounds like a bug, any idea on a repro?
7. Not clear what's meant here, will need to see example

**Comment by NanakoAC** [comment] 2020-05-24 01:00
ah my bad on 2, it was accidentally set to 1x multiplier, will fix

**Comment by Ketrai** [comment] 2020-05-24 01:16
6. should be able to be reproduced by cutting off an arm, then rejuvinating the tripod.

**Comment by Ketrai** [comment] 2020-05-24 01:17
7. CTRL + ALT click a wall, you'll go inside of it. you can then walk into an unobstructed tile to ignore said wall...

**Comment by Ketrai** [comment] 2020-05-24 01:18
1. buckle tripod to chair, then go to another room as a human. you'll see the tripod sprite lit up from certain angles despite not being able to see it mechanically.

**Comment by Snypehunter007** [comment] 2020-05-28 23:35
@NanakoAC Is everything mentioned fixed with that branch?

**Comment by Snypehunter007** [comment] 2020-07-02 10:06
Locking.

**Closed as completed by Snypehunter007** 2020-07-02 10:06 UTC
Labels: Fixed
