### ISSUE TITLE
BUG: Plasma cutter lacks a projectile sprite

### ISSUE THREAD

**Issue by Cairo283** [DS-13-Dev-Team/DS13-1.0#196] opened 2020-03-29 00:06 UTC
#### Description of issue

Plasma Cutter projectiles lack a sprite, resulting in them being invisible.

#### Difference between expected and actual behavior

For the plasma cutter's shots to have an icon.

#### Steps to reproduce 

Shoot a plasma cutter.

#### Specific information for locating

mining cutter

#### Length of time in which bug has been known to occur

I assume since it was made possible to fire the cutter.

#### Client version, Server revision & Game ID

893d8ac3e599a5a251b539ca4d0d47f7312709d4 - dev - 2020-03-28

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by NanakoAC** [comment] 2020-03-29 01:05
Working as intended. It fires an invisible beam in dead space 2. All you can see is the flash at the gun, and the effect on hit

**Comment by Snypehunter007** [comment] 2020-03-29 01:41
Like Nanako said, intentional.

Closing.

**Closed as completed by Snypehunter007** 2020-03-29 01:41 UTC
Labels: Fixed
