### ISSUE TITLE
Strange screen offset

### ISSUE THREAD

**Issue by Tomdoot** [DS-13-Dev-Team/DS13-1.0#198] opened 2020-03-29 01:15 UTC
#### Description of issue
Upon returning from SSD in a locker, my screen was offset to the right and up by a lot.
 It also shifted occasionally. 

#### Difference between expected and actual behavior
Upon returning from SSD, my screen should be normal.

#### Steps to reproduce 
Probably: Enter locker. Go SSD.

#### Specific information for locating

Could have something to do with screen offset from gunfire, but my character never had a gun at that point.

#### Length of time in which bug has been known to occur

The testround on the 28th.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 893d8ac3e599a5a251b539ca4d0d47f7312709d4 - dev - 2020-03-28
Game ID: b6p-aaUg
Current map: USG Ishimura

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by NanakoAC** [comment] 2020-03-29 01:57
I've fixed two causes of this but it keeps sneaking through

The problem is the client's view and temp_view vars becoming desynchronised. I'm not sure how this could happen, but it would be helpful to have a reliable way to reproduce it

**Comment by Snypehunter007** [comment] 2020-05-14 21:26
Duplicate of #173. Closing.

**Closed as completed by Snypehunter007** 2020-05-14 21:26 UTC
Labels: Duplicate
