### ISSUE TITLE
Bug: Heavy Pulse Rifle Shot Spread

### ISSUE THREAD

**Issue by YellowKingThe** [DS-13-Dev-Team/DS13-1.0#1649] opened 2021-09-11 02:05 UTC
#### Description of issue:
The Heavy Pulse Rifle has massive spread even with good skill, with trained ranged weapons skill my shots will go off at a 90 degree angle away from where I am aiming.

#### Difference between expected and actual behavior:
Heavy pulse should be useable with trained skill and not fire off in the entirely wrong direction with any level of skill invested.

#### Steps to reproduce:
Test Heavy Pulse rifle on different skill levels of skill.

**Comment by NanakoAC** [comment] 2021-09-12 06:23
its not a bug, massive spray is how its designed to work.

Treat the HPR like a big sidearm. Pull it out to spray into large crowds or at a big target, then set it down to cool and fight with a different weapon for a while
it's not ever going to be an accurate or efficient tool, that's why it has infinite ammo!

**Comment by Snypehunter007** [comment] 2021-09-30 19:47
Working as intended and reduced the dispersion on HPR rounds recently.

Closing.

**Closed as completed by Snypehunter007** 2021-09-30 19:47 UTC
Labels: Working as Intended
